
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.floresbarco.analyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Plus = 7;
  public static final int DoublePercent = 18;
  public static final int Asterisk = 8;
  public static final int Colon = 14;
  public static final int Character = 22;
  public static final int SingleQuotes = 5;
  public static final int VerticalBar = 10;
  public static final int Comma = 12;
  public static final int Arrow = 17;
  public static final int QuotationMarks = 4;
  public static final int CurlyBracket2 = 16;
  public static final int CurlyBracket1 = 15;
  public static final int QuestionMarck = 9;
  public static final int Semicolon = 13;
  public static final int LineBreak = 2;
  public static final int Conj = 3;
  public static final int EOF = 0;
  public static final int Dash = 11;
  public static final int error = 1;
  public static final int Digit = 19;
  public static final int Letter = 21;
  public static final int String = 20;
  public static final int Dot = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LineBreak",
  "Conj",
  "QuotationMarks",
  "SingleQuotes",
  "Dot",
  "Plus",
  "Asterisk",
  "QuestionMarck",
  "VerticalBar",
  "Dash",
  "Comma",
  "Semicolon",
  "Colon",
  "CurlyBracket1",
  "CurlyBracket2",
  "Arrow",
  "DoublePercent",
  "Digit",
  "String",
  "Letter",
  "Character"
  };
}

